apiVersion: apps/v1
kind: Deployment
metadata:
  name: birdshop
  labels:
    app: birdshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: birdshop
  template:
    metadata:
      labels:
        app: birdshop
    spec:
      containers:
      - name: birdshop
        image: ecommerce:latest
        imagePullPolicy: Never # Added a specific tag for better version control
        ports:
        - containerPort: 80
